syntax = "proto3";

package metrics;

option go_package = "github.com/bluegopher/go-musthave-metrics-tpl/internal/proto";

// Metric определяет единичную метрику.
message Metric {
  string id = 1;

  enum MType {
    GAUGE = 0;
    COUNTER = 1;
  }

  MType  type  = 2;
  int64  delta = 3;
  double value = 4;
}

// UpdateMetricsRequest содержит список метрик для обновления.
message UpdateMetricsRequest {
  repeated Metric metrics = 1;
}

// UpdateMetricsResponse — пустой ответ.
message UpdateMetricsResponse {}

service Metrics {
  rpc UpdateMetrics(UpdateMetricsRequest) returns (UpdateMetricsResponse);
}
